using AccountingTestingPlatform.Report;
using AccountingTestingPlatform.Test.TypeTests.ConsistencyTest.ConcreteTests;
using AccountingTestingPlatform.Test.TypeTests.RecursosExercicioTest.ConcreteTests;
using AccountingTestingPlatform.Test.TypeTests.SaldosInvertidosTest.ConcreteTests;
using AccountingTestingPlatform.Test.TypeTests.SaldosPorNivelTest.ConcreteTests;
using AccountingTestingPlatform.Test.TypeTests.SaldosSuperavitTest.ConcreteTests;
using Npgsql;

namespace AccountingTestingPlatform.Profile;

class EncerramentoMensalProfileTest : ProfileTestBase
{
    public EncerramentoMensalProfileTest(NpgsqlConnection connection, string remessa, IReport report)
    {
        TestList.Add(new FechamentoContasPatrimoniaisTest(connection, remessa, report));
        TestList.Add(new FechamentoContasOrcamentariasTest(connection, remessa, report));
        TestList.Add(new FechamentoContasControlesTest(connection, remessa, report));
        TestList.Add(new SaldosPorNivelContasOrcamentariasTest(connection, remessa, report));
        TestList.Add(new SaldosPorNivelContasControleTest(connection, remessa, report));
        TestList.Add(new SaldoRecisoesTest(connection, remessa, report));
        TestList.Add(new SaldoTercoFeriasTest(connection, remessa, report));
        TestList.Add(new SaldoOutrosAdiantamentosAPessoalTest(connection, remessa, report));
        TestList.Add(new SuprimentosFundosTest(connection, remessa, report));
        TestList.Add(new RendimentoLegislativoAntecipadoDuodecimoTest(connection, remessa, report));
        TestList.Add(new ParceriasTest(connection, remessa, report));
        TestList.Add(new PrecatoriosCurtoPrazoTest(connection, remessa, report));
        TestList.Add(new PrecatoriosLongoPrazoTest(connection, remessa, report));
        TestList.Add(new ContribuicaoRPPSAPagarTest(connection, remessa, report));
        TestList.Add(new ContribuicaoRGPSAPagarTest(connection, remessa, report));
        TestList.Add(new FgtsAPagarTest(connection, remessa, report));
        TestList.Add(new PassivoRestosAPagarTest(connection, remessa, report));
        TestList.Add(new PasepAPagarTest(connection, remessa, report));
        TestList.Add(new PrevisaoInicialReceitaBrutaTest(connection, remessa, report));
        TestList.Add(new PrevisaoInicialDeducaoRenunciaTest(connection, remessa, report));
        TestList.Add(new PrevisaoInicialDeducaoFundebTest(connection, remessa, report));
        TestList.Add(new PrevisaoInicialDeducaoOutrasTest(connection, remessa, report));
        TestList.Add(new ReestimativaReceitaTest(connection, remessa, report));
        TestList.Add(new CreditoInicialTest(connection, remessa, report));
        TestList.Add(new CreditoSuplementarAbertoTest(connection, remessa, report));
        TestList.Add(new CreditoEspecialAbertoTest(connection, remessa, report));
        TestList.Add(new CreditoEspecialReabertoTest(connection, remessa, report));
        TestList.Add(new CreditoExtraordinarioAbertoTest(connection, remessa, report));
        TestList.Add(new CreditoExtraordinarioReabertoTest(connection, remessa, report));
        TestList.Add(new CreditoAdicionalSuperavitTest(connection, remessa, report));
        TestList.Add(new CreditoAdicionalExcessoTest(connection, remessa, report));
        TestList.Add(new CreditoAdicionalAnulacaoTest(connection, remessa, report));
        TestList.Add(new AnulacaoDotacaoEntreEntidadesTest(connection, remessa, report));
        TestList.Add(new AnulacaoDotacaoMesmaEntidadesTest(connection, remessa, report));
        TestList.Add(new ValorGlobalDotacaoAdicionalTest(connection, remessa, report));
        TestList.Add(new CancelamentoDotacoesTest(connection, remessa, report));
        TestList.Add(new ValorEmpenhadoTest(connection, remessa, report));
        TestList.Add(new RpNpInscritosUltimoExercicioTest(connection, remessa, report));
        TestList.Add(new RpNpInscritosExercicioAnteriorTest(connection, remessa, report));
        TestList.Add(new RpNpInscritosInscricaoNoExercicio(connection, remessa, report));
        TestList.Add(new RpPInscritosUltimoExercicioTest(connection, remessa, report));
        TestList.Add(new RpPInscritosExerciciosAnterioresTest(connection, remessa, report));
        TestList.Add(new RpPInscritosInscricaoNoExercicio(connection, remessa, report));
        TestList.Add(new ReceitaARealizarTest(connection, remessa, report));
        TestList.Add(new ReceitaBrutaRealizadaTest(connection, remessa, report));
        TestList.Add(new DeducaoFundebRealizadaTest(connection, remessa, report));
        TestList.Add(new DeducaoRenunciaRealizadaTest(connection, remessa, report));
        TestList.Add(new DeducaoOutrasRealizadaTest(connection, remessa, report));
        TestList.Add(new CreditoDisponivelTest(connection, remessa, report));
        TestList.Add(new CreditoEmpenhadoALiquidarTest(connection, remessa, report));
        TestList.Add(new CreditoEmpenhadoLiquidadoAPagarTest(connection, remessa, report));
        TestList.Add(new CreditoEmpenhadoLiquidadoPagoTest(connection, remessa, report));
        TestList.Add(new AnulacaoEmpenhosTest(connection, remessa, report));
        TestList.Add(new EmpenhosALiquidar(connection, remessa, report));
        TestList.Add(new EmpenhosLiquidadosAPagarTest(connection, remessa, report));
        TestList.Add(new EmpenhosLiquidadosPagosTest(connection, remessa, report));
        TestList.Add(new RpNpALiquidarTest(connection, remessa, report));
        TestList.Add(new RpNpLiquidadoAPagarTest(connection, remessa, report));
        TestList.Add(new RpNpPagoTest(connection, remessa, report));
        TestList.Add(new RpNpInscritoExercicioTest(connection, remessa, report));
        TestList.Add(new RpNpCanceladosTest(connection, remessa, report));
        TestList.Add(new RpPAPagarTest(connection, remessa, report));
        TestList.Add(new RpPPagoTest(connection, remessa, report));
        TestList.Add(new RpPInscritoExercicioTest(connection, remessa, report));
        TestList.Add(new RpPCanceladosTest(connection, remessa, report));
        TestList.Add(new DdrTest(connection, remessa, report));
        TestList.Add(new DdrEmpenhadaTest(connection, remessa, report));
        TestList.Add(new DdrLiquidadaTest(connection, remessa, report));
        TestList.Add(new RetencoesTest(connection, remessa, report));
        TestList.Add(new DdrRetencoesTest(connection, remessa, report));
        TestList.Add(new RateioCofronTest(connection, remessa, report));
        TestList.Add(new RateioCisaTest(connection, remessa, report));
        TestList.Add(new VpdDeducaoFundebRealizadaTest(connection, remessa, report));
        TestList.Add(new CoAspsTest(connection, remessa, report));
        TestList.Add(new CoMdeTest(connection, remessa, report));
        TestList.Add(new ParcelamentoRppsCurtoPrazoTest(connection, remessa, report));
        TestList.Add(new ParcelamentoRppsLongoPrazoTest(connection, remessa, report));
        TestList.Add(new BensMoveisAClassificarTest(connection, remessa, report));
        TestList.Add(new CpDeducaoFundebTest(connection, remessa, report));
        TestList.Add(new Modalidade93NaoConsorcioTest(connection, remessa, report));
        TestList.Add(new Modalidade71NaoConsorcioTest(connection, remessa, report));
        TestList.Add(new ContribuicaoPatronalNormalFpsmTest(connection, remessa, report));
        TestList.Add(new ContribuicaoPatronalSuplementarFpsmTest(connection, remessa, report));
        TestList.Add(new AportePeriodicoFpsmTest(connection, remessa, report));
        TestList.Add(new ContribuicaoServidoresFpsmTest(connection, remessa, report));
        TestList.Add(new DisponibilidadesTest(connection, remessa, report));
        TestList.Add(new DuodecimoVpaVpdTest(connection, remessa, report));
        TestList.Add(new DuodecimoRepasseTest(connection, remessa, report));
        TestList.Add(new FrImpostosTest(connection, remessa, report));
        TestList.Add(new AtivoPassivoIntraTest(connection, remessa, report));
        TestList.Add(new VpaVpdIntraTest(connection, remessa, report));
        TestList.Add(new ReceitaDespesaIntraTest(connection, remessa, report));
        TestList.Add(new SaldoPlIntraTest(connection, remessa, report));
        TestList.Add(new DuodecimoVpaVpdInscricaoTest(connection, remessa, report));
        TestList.Add(new ValorAtualAmortizacaoPassivoAtuarialTest(connection, remessa, report));
        TestList.Add(new DiariasAPagarTest(connection, remessa, report));
        TestList.Add(new ResultadoExercicioConsolidacaoTest(connection, remessa, report));
        TestList.Add(new ResultadoExercicioIntraTest(connection, remessa, report));
        TestList.Add(new ResultadoExercicioInterUniaoTest(connection, remessa, report));
        TestList.Add(new ResultadoExercicioInterEstadoTest(connection, remessa, report));
        TestList.Add(new ResultadoExercicioInterMunicipioTest(connection, remessa, report));
        TestList.Add(new SaldosInvertidosTest(connection, remessa, report));
        TestList.Add(new RecursosExercicioTest(connection, remessa, report));
        TestList.Add(new SaldosSuperavitTest(connection, remessa, report));


        //TestList.Add(new FailTest(connection, remessa, report));
    }
}
